// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  menu_item: dynamic(() => import("./MenuItem")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
};
